export * from "./applicant";
export * from "./lead";
export * from "./soProcessNew";
export * from "./coProcess";
export * from "./l1creditSanction";
export * from "./l2creditSanction";
export * from "./sampleForm";
export * from "./documentation";
export * from "./makersForm";
export * from "./checkersForm";
export * from "./cifGeneration";
export * from "./fieldInspection";
export * from "./soProcessExisting";
export * from "./backOfficeVerification";
export * from "./finalDisbursement";
export { default as samplewidget } from "./sampleWidget";
export { default as applicantwidget } from "./applicantWidget";
export { default as leadwidget } from "./leadWidget";
export * from "./finalApproval";
export * from "./creditScore";